# Generated by Django 4.1.7 on 2023-03-21 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelbedsDestinationLocation',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('countryCode', models.CharField(max_length=3)),
                ('isoCode', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsFacilityGroup',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsFacilityTypology',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('numberFlag', models.BooleanField()),
                ('logicFlag', models.BooleanField()),
                ('feeFlag', models.BooleanField()),
                ('distanceFlag', models.BooleanField()),
                ('ageFromFlag', models.BooleanField()),
                ('ageToFlag', models.BooleanField()),
                ('dateFromFlag', models.BooleanField()),
                ('dateToFlag', models.BooleanField()),
                ('timeFromFlag', models.BooleanField()),
                ('timeToFlag', models.BooleanField()),
                ('indYesOrNoFlag', models.BooleanField()),
                ('amountFlag', models.BooleanField()),
                ('currencyFlag', models.BooleanField()),
                ('appTypeFlag', models.BooleanField()),
                ('textFlag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsFacility',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('facilityGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacilitygroup')),
                ('facilityTypology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacilitytypology')),
            ],
        ),
    ]
