# Generated by Django 4.1.7 on 2023-03-21 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hotelbedsdestinationlocation_hotelbedsfacilitygroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelbedsAccommodation',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('typeMultiDescription', models.CharField(max_length=255)),
                ('typeDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsCategory',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('simpleCode', models.IntegerField()),
                ('accommodationType', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsChain',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsGroupCategory',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotel',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('countryCode', models.CharField(max_length=3)),
                ('stateCode', models.CharField(max_length=3)),
                ('destinationCode', models.CharField(max_length=5)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('web', models.CharField(max_length=255)),
                ('ranking', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('accommodationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsaccommodation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedscategory')),
                ('categoryGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsgroupcategory')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedschain')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomCode', models.CharField(max_length=255)),
                ('isParentRoom', models.BooleanField()),
                ('minPax', models.IntegerField()),
                ('maxPax', models.IntegerField()),
                ('maxAdults', models.IntegerField()),
                ('maxChildren', models.IntegerField()),
                ('minAdults', models.IntegerField()),
                ('characteristicCode', models.CharField(max_length=255)),
                ('PMSRoomCode', models.CharField(max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.hotelbedshotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelRoomStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stayType', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomStays', to='api.hotelbedshotelroom')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsImageType',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsRoom',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('characteristic', models.CharField(max_length=100)),
                ('minPax', models.IntegerField()),
                ('maxPax', models.IntegerField()),
                ('maxAdults', models.IntegerField()),
                ('maxChildren', models.IntegerField()),
                ('minAdults', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('typeDescription', models.CharField(max_length=100)),
                ('characteristicDescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsSegment',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelWildcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(max_length=255)),
                ('characteristicCode', models.CharField(max_length=255)),
                ('hotelRoomDescription', models.CharField(max_length=255)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildcards', to='api.hotelbedshotel')),
                ('roomCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsroom')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelRoomStayFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacility')),
                ('facilityGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacilitygroup')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomStayFacilities', to='api.hotelbedshotelroomstay')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelRoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indLogic', models.BooleanField(null=True)),
                ('indYesOrNo', models.BooleanField(null=True)),
                ('number', models.IntegerField()),
                ('voucher', models.BooleanField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacility')),
                ('facilityGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacilitygroup')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomFacilities', to='api.hotelbedshotelroom')),
            ],
        ),
        migrations.AddField(
            model_name='hotelbedshotelroom',
            name='roomType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsroom'),
        ),
        migrations.CreateModel(
            name='HotelbedsHotelPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=20)),
                ('phoneType', models.CharField(max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.hotelbedshotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelInterestPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('poiName', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacility')),
                ('facilityGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacilitygroup')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interestPoints', to='api.hotelbedshotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('roomCode', models.CharField(max_length=255, null=True)),
                ('characteristicCode', models.CharField(max_length=255, null=True)),
                ('order', models.IntegerField()),
                ('visualOrder', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.hotelbedshotel')),
                ('imageType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsimagetype')),
                ('roomType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsroom')),
            ],
        ),
        migrations.CreateModel(
            name='HotelbedsHotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('number', models.IntegerField()),
                ('voucher', models.BooleanField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacility')),
                ('facilityGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsfacilitygroup')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='api.hotelbedshotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotelbedshotel',
            name='segments',
            field=models.ManyToManyField(to='api.hotelbedssegment'),
        ),
        migrations.AddField(
            model_name='hotelbedscategory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsgroupcategory'),
        ),
    ]
