# Generated by Django 4.1.7 on 2023-03-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hotelbedsaccommodation_hotelbedscategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbedsfacility',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedsgroupcategory',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotelbedsroom',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedsroom',
            name='typeDescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
