# Generated by Django 4.1.7 on 2023-03-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_hotelbedsroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbedsroom',
            name='characteristicDescription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
