# Generated by Django 4.1.7 on 2023-03-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hotelbedsroom_characteristicdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbedsgroupcategory',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbedsgroupcategory',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
