# Generated by Django 4.1.7 on 2023-03-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_hotelbedsgroupcategory_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelbedsClassification',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
