# Generated by Django 4.1.7 on 2023-03-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_hotelbedsclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbedshotel',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelbedshotelroom',
            name='PMSRoomCode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
