# Generated by Django 4.1.7 on 2023-03-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_hotelbedshotel_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelbedsHotelInterestPoints',
            new_name='HotelbedsHotelInterestPoint',
        ),
    ]
