# Generated by Django 4.1.7 on 2023-03-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hotelbedshotelroomfacility_indfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbedshotelwildcard',
            name='characteristicCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelbedshotelwildcard',
            name='roomCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotelbedshotelwildcard',
            name='roomType',
            field=models.CharField(max_length=20),
        ),
    ]
