# Generated by Django 4.1.7 on 2023-03-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_hotelbedshotelimage_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbedshotelroom',
            name='roomType',
            field=models.CharField(max_length=20),
        ),
    ]
