# Generated by Django 4.1.7 on 2023-03-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_hotelbedshotel_accommodationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbedshotel',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedshotel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedscategory'),
        ),
        migrations.AlterField(
            model_name='hotelbedshotel',
            name='categoryGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsgroupcategory'),
        ),
        migrations.AlterField(
            model_name='hotelbedshotel',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedshotel',
            name='postalCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
