# Generated by Django 4.1.7 on 2023-03-22 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_hotelbedshotel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbedscategory',
            name='accommodationType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedscategory',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedscategory',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hotelbedsgroupcategory'),
        ),
        migrations.AlterField(
            model_name='hotelbedscategory',
            name='simpleCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedschain',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbedsclassification',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
