# Generated by Django 4.1.7 on 2023-04-03 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_hotelbedscategory_accommodationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stripe_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
