# Generated by Django 4.1.7 on 2023-03-26 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_alter_hotelbedscategory_accommodationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='travel_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
