# Generated by Django 4.1.7 on 2023-04-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_account_user'),
        ('api', '0019_rename_guest_count_booking_adults_and_more'),
    ]

    operations = [
    ]
