# Generated by Django 4.1.7 on 2023-04-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20230406_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='points_spent',
            field=models.IntegerField(default=0),
        ),
    ]
