# Generated by Django 4.1.7 on 2023-04-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_booking_overlapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
    ]
