# Generated by Django 4.1.7 on 2023-04-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_booking_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
