# Generated by Django 4.1.7 on 2023-04-25 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_booking_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rebooked_to',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rebooked_from', to='api.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('CO', 'Confirmed'), ('CA', 'Canceled'), ('RE', 'Rebooked'), ('IP', 'In Progress'), ('PA', 'Past')], default='PE', max_length=2),
        ),
    ]
