# Generated by Django 4.1.7 on 2023-04-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_booking_rebooked_to_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='stripe_id',
            new_name='stripe_payment_intent_id',
        ),
    ]
