# Generated by Django 4.1.7 on 2023-04-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_stripe_id_booking_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_refund_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
