# Generated by Django 4.1.7 on 2023-04-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_booking_stripe_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelation_status',
            field=models.CharField(choices=[('N', 'None'), ('F', 'Full'), ('P', 'Partial')], default=None, max_length=2, null=True),
        ),
    ]
