# Generated by Django 4.1.7 on 2023-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_booking_cancelation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.FloatField(default=0),
        ),
    ]
