# Generated by Django 4.1.7 on 2023-04-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_booking_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
