# Generated by Django 4.1.7 on 2023-04-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_booking_canceled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='autofill_booking_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
