# Generated by Django 4.1.7 on 2023-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_account_autofill_booking_info_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_before_fees_tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_before_fees_tax_and_discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_discount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_fees_taxes',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='card_last_four',
            field=models.CharField(default='4242', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='card_network',
            field=models.CharField(default='visa', max_length=20),
            preserve_default=False,
        ),
    ]
