# Generated by Django 4.1.7 on 2023-04-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_booking_amount_before_fees_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_original_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
