# Generated by Django 4.1.7 on 2023-04-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_booking_amount_original_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount_original_total',
        ),
    ]
