# Generated by Django 4.1.7 on 2023-04-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_booking_stripe_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_customer_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
