Table User {
  id integer
  email varchar(200)
  travel_points integer
  username varchar(60)
  password varchar(200)
  created_at timestamp
}

Enum PropertyType {
  Hotel
  Motel
}

Table Property {
  id int [pk, increment]
  first_name varchar(40)
  last_name  varchar(40)
  type PropertyType
  address varchar(200)
  city varchar(50)
  state varchar(50)
  zip varchar(10)
  country varchar(3)
}

Enum BookingStatus {
  Pending
  Confirmed
  Cancelled
  Past
}

Table Booking {
  id int [pk, increment]
  stripe_id varchar(200)
  points_earned integer
  status BookingStatus
  property_id int [ref: > Property.id]
  user_id int [ref: > User.id]
  start_date date
  end_date date
  created_at timestamp
}

Table Review {
  id int [pk, increment]
  property_id int [ref: > Property.id]
  user_id int [ref: > User.id]
  rating int
  comment varchar(200)
  created_at timestamp
}

Table Image {
  id int [pk, increment]
  property_id int [ref: > Property.id]
  url varchar(200)
  created_at timestamp
}

